const consonants = [
	{ letter: "ก", name: "ก ไก่" },
	{ letter: "ข", name: "ข ไข่" },
	{ letter: "ฃ", name: "ฃ ขวด" },
	{ letter: "ค", name: "ค ควาย" },
	{ letter: "ฅ", name: "ฅ คน" },
	{ letter: "ฆ", name: "ฆ ระฆัง" },
	{ letter: "ง", name: "ง งู" },
	{ letter: "จ", name: "จ จาน" },
	{ letter: "ฉ", name: "ฉ ฉิ่ง" },
	{ letter: "ช", name: "ช ช้าง" },
	{ letter: "ซ", name: "ซ โซ่" },
	{ letter: "ฌ", name: "ฌ เฌอ" },
	{ letter: "ญ", name: "ญ หญิง" },
	{ letter: "ฎ", name: "ฎ ชฎา" },
	{ letter: "ฏ", name: "ฏ ปฏัก" },
	{ letter: "ฐ", name: "ฐ ฐาน" },
	{ letter: "ฑ", name: "ฑ มณโฑ" },
	{ letter: "ฒ", name: "ฒ ผู้เฒ่า" },
	{ letter: "ณ", name: "ณ เณร" },
	{ letter: "ด", name: "ด เด็ก" },
	{ letter: "ต", name: "ต เต่า" },
	{ letter: "ถ", name: "ถ ถุง" },
	{ letter: "ท", name: "ท ทหาร" },
	{ letter: "ธ", name: "ธ ธง" },
	{ letter: "น", name: "น หนู" },
	{ letter: "บ", name: "บ ใบไม้" },
	{ letter: "ป", name: "ป ปลา" },
	{ letter: "ผ", name: "ผ ผึ้ง" },
	{ letter: "ฝ", name: "ฝ ฝา" },
	{ letter: "พ", name: "พ พาน" },
	{ letter: "ฟ", name: "ฟ ฟัน" },
	{ letter: "ภ", name: "ภ สำเภา" },
	{ letter: "ม", name: "ม ม้า" },
	{ letter: "ย", name: "ย ยักษ์" },
	{ letter: "ร", name: "ร เรือ" },
	{ letter: "ล", name: "ล ลิง" },
	{ letter: "ว", name: "ว แหวน" },
	{ letter: "ศ", name: "ศ ศาลา" },
	{ letter: "ษ", name: "ษ ฤๅษี" },
	{ letter: "ส", name: "ส เสือ" },
	{ letter: "ห", name: "ห หีบ" },
	{ letter: "ฬ", name: "ฬ จุฬา" },
	{ letter: "อ", name: "อ อ่าง" },
	{ letter: "ฮ", name: "ฮ นกฮูก" },
];

export default consonants;
