const consonants = [
	{ letter: "ก", name: "ก ไก่", phonetic: "gɔɔ gài" },
	{ letter: "ข", name: "ข ไข่", phonetic: "kʰɔ̌ɔ kʰài" },
	{ letter: "ฃ", name: "ฃ ขวด", phonetic: "kʰɔ̌ɔ kʰùat" },
	{ letter: "ค", name: "ค ควาย", phonetic: "kʰɔɔ kʰwaai" },
	{ letter: "ฅ", name: "ฅ คน", phonetic: "kʰɔɔ kʰon" },
	{ letter: "ฆ", name: "ฆ ระฆัง", phonetic: "kʰɔɔ rá-kʰang" },
	{ letter: "ง", name: "ง งู", phonetic: "ngɔɔ nguu" },
	{ letter: "จ", name: "จ จาน", phonetic: "jɔɔ jaan" },
	{ letter: "ฉ", name: "ฉ ฉิ่ง", phonetic: "chʰɔ̌ɔ chìng" },
	{ letter: "ช", name: "ช ช้าง", phonetic: "chʰɔɔ chʰáang" },
	{ letter: "ซ", name: "ซ โซ่", phonetic: "sɔɔ sôo" },
	{ letter: "ฌ", name: "ฌ เฌอ", phonetic: "chʰɔɔ chʰəə" },
	{ letter: "ญ", name: "ญ หญิง", phonetic: "yɔɔ yǐng" },
	{ letter: "ฎ", name: "ฎ ชฎา", phonetic: "dɔɔ chá-daa" },
	{ letter: "ฏ", name: "ฏ ปฏัก", phonetic: "dtɔɔ bpà-tàk" },
	{ letter: "ฐ", name: "ฐ ฐาน", phonetic: "tʰɔ̌ɔ tʰǎan" },
	{ letter: "ฑ", name: "ฑ มณโฑ", phonetic: "tʰɔɔ mon-tʰoo" },
	{ letter: "ฒ", name: "ฒ ผู้เฒ่า", phonetic: "tʰɔɔ pʰûu-tʰâo" },
	{ letter: "ณ", name: "ณ เณร", phonetic: "nɔɔ neen" },
	{ letter: "ด", name: "ด เด็ก", phonetic: "dɔɔ dèk" },
	{ letter: "ต", name: "ต เต่า", phonetic: "dtɔɔ dtào" },
	{ letter: "ถ", name: "ถ ถุง", phonetic: "tʰɔ̌ɔ tʰǔng" },
	{ letter: "ท", name: "ท ทหาร", phonetic: "tʰɔɔ tʰá-hǎan" },
	{ letter: "ธ", name: "ธ ธง", phonetic: "tʰɔɔ tʰong" },
	{ letter: "น", name: "น หนู", phonetic: "nɔɔ nǔu" },
	{ letter: "บ", name: "บ ใบไม้", phonetic: "bɔɔ bai-máai" },
	{ letter: "ป", name: "ป ปลา", phonetic: "bpɔɔ bplaa" },
	{ letter: "ผ", name: "ผ ผึ้ง", phonetic: "pʰɔ̌ɔ pʰɯ̂ng" },
	{ letter: "ฝ", name: "ฝ ฝา", phonetic: "fɔ̌ɔ fǎa" },
	{ letter: "พ", name: "พ พาน", phonetic: "pʰɔɔ pʰaan" },
	{ letter: "ฟ", name: "ฟ ฟัน", phonetic: "fɔɔ fan" },
	{ letter: "ภ", name: "ภ สำเภา", phonetic: "pʰɔɔ sǎm-pʰao" },
	{ letter: "ม", name: "ม ม้า", phonetic: "mɔɔ máa" },
	{ letter: "ย", name: "ย ยักษ์", phonetic: "yɔɔ yák" },
	{ letter: "ร", name: "ร เรือ", phonetic: "rɔɔ rɯa" },
	{ letter: "ล", name: "ล ลิง", phonetic: "lɔɔ ling" },
	{ letter: "ว", name: "ว แหวน", phonetic: "wɔɔ wɛ̌ɛn" },
	{ letter: "ศ", name: "ศ ศาลา", phonetic: "sɔ̌ɔ sǎa-laa" },
	{ letter: "ษ", name: "ษ ฤๅษี", phonetic: "sɔ̌ɔ rɯɯ-sǐi" },
	{ letter: "ส", name: "ส เสือ", phonetic: "sɔ̌ɔ sɯ̌a" },
	{ letter: "ห", name: "ห หีบ", phonetic: "hɔ̌ɔ hìip" },
	{ letter: "ฬ", name: "ฬ จุฬา", phonetic: "lɔɔ jù-laa" },
	{ letter: "อ", name: "อ อ่าง", phonetic: "ʔɔɔ àang" },
	{ letter: "ฮ", name: "ฮ นกฮูก", phonetic: "hɔɔ nók-hûuk" },
];

export default consonants;
