const consonants = [
	{ letter: "ก", name: "ก ไก่", phonetic: "gɔɔ gài", class: "middle" },
	{ letter: "ข", name: "ข ไข่", phonetic: "kʰɔ̌ɔ kʰài", class: "high" },
	{ letter: "ฃ", name: "ฃ ขวด", phonetic: "kʰɔ̌ɔ kʰùat", class: "high" },
	{ letter: "ค", name: "ค ควาย", phonetic: "kʰɔɔ kʰwaai", class: "low" },
	{ letter: "ฅ", name: "ฅ คน", phonetic: "kʰɔɔ kʰon", class: "low" },
	{ letter: "ฆ", name: "ฆ ระฆัง", phonetic: "kʰɔɔ rá-kʰang", class: "low" },
	{ letter: "ง", name: "ง งู", phonetic: "ngɔɔ nguu", class: "low" },
	{ letter: "จ", name: "จ จาน", phonetic: "jɔɔ jaan", class: "middle" },
	{ letter: "ฉ", name: "ฉ ฉิ่ง", phonetic: "chʰɔ̌ɔ chìng", class: "high" },
	{ letter: "ช", name: "ช ช้าง", phonetic: "chʰɔɔ chʰáang", class: "low" },
	{ letter: "ซ", name: "ซ โซ่", phonetic: "sɔɔ sôo", class: "low" },
	{ letter: "ฌ", name: "ฌ เฌอ", phonetic: "chʰɔɔ chʰəə", class: "low" },
	{ letter: "ญ", name: "ญ หญิง", phonetic: "yɔɔ yǐng", class: "low" },
	{ letter: "ฎ", name: "ฎ ชฎา", phonetic: "dɔɔ chá-daa", class: "middle" },
	{ letter: "ฏ", name: "ฏ ปฏัก", phonetic: "dtɔɔ bpà-tàk", class: "middle" },
	{ letter: "ฐ", name: "ฐ ฐาน", phonetic: "tʰɔ̌ɔ tʰǎan", class: "high" },
	{ letter: "ฑ", name: "ฑ มณโฑ", phonetic: "tʰɔɔ mon-tʰoo", class: "low" },
	{ letter: "ฒ", name: "ฒ ผู้เฒ่า", phonetic: "tʰɔɔ pʰûu-tʰâo", class: "low" },
	{ letter: "ณ", name: "ณ เณร", phonetic: "nɔɔ neen", class: "low" },
	{ letter: "ด", name: "ด เด็ก", phonetic: "dɔɔ dèk", class: "middle" },
	{ letter: "ต", name: "ต เต่า", phonetic: "dtɔɔ dtào", class: "middle" },
	{ letter: "ถ", name: "ถ ถุง", phonetic: "tʰɔ̌ɔ tʰǔng", class: "high" },
	{ letter: "ท", name: "ท ทหาร", phonetic: "tʰɔɔ tʰá-hǎan", class: "low" },
	{ letter: "ธ", name: "ธ ธง", phonetic: "tʰɔɔ tʰong", class: "low" },
	{ letter: "น", name: "น หนู", phonetic: "nɔɔ nǔu", class: "low" },
	{ letter: "บ", name: "บ ใบไม้", phonetic: "bɔɔ bai-máai", class: "middle" },
	{ letter: "ป", name: "ป ปลา", phonetic: "bpɔɔ bplaa", class: "middle" },
	{ letter: "ผ", name: "ผ ผึ้ง", phonetic: "pʰɔ̌ɔ pʰɯ̂ng", class: "high" },
	{ letter: "ฝ", name: "ฝ ฝา", phonetic: "fɔ̌ɔ fǎa", class: "high" },
	{ letter: "พ", name: "พ พาน", phonetic: "pʰɔɔ pʰaan", class: "low" },
	{ letter: "ฟ", name: "ฟ ฟัน", phonetic: "fɔɔ fan", class: "low" },
	{ letter: "ภ", name: "ภ สำเภา", phonetic: "pʰɔɔ sǎm-pʰao", class: "low" },
	{ letter: "ม", name: "ม ม้า", phonetic: "mɔɔ máa", class: "low" },
	{ letter: "ย", name: "ย ยักษ์", phonetic: "yɔɔ yák", class: "low" },
	{ letter: "ร", name: "ร เรือ", phonetic: "rɔɔ rɯa", class: "low" },
	{ letter: "ล", name: "ล ลิง", phonetic: "lɔɔ ling", class: "low" },
	{ letter: "ว", name: "ว แหวน", phonetic: "wɔɔ wɛ̌ɛn", class: "low" },
	{ letter: "ศ", name: "ศ ศาลา", phonetic: "sɔ̌ɔ sǎa-laa", class: "high" },
	{ letter: "ษ", name: "ษ ฤๅษี", phonetic: "sɔ̌ɔ rɯɯ-sǐi", class: "high" },
	{ letter: "ส", name: "ส เสือ", phonetic: "sɔ̌ɔ sɯ̌a", class: "high" },
	{ letter: "ห", name: "ห หีบ", phonetic: "hɔ̌ɔ hìip", class: "high" },
	{ letter: "ฬ", name: "ฬ จุฬา", phonetic: "lɔɔ jù-laa", class: "low" },
	{ letter: "อ", name: "อ อ่าง", phonetic: "ʔɔɔ àang", class: "middle" },
	{ letter: "ฮ", name: "ฮ นกฮูก", phonetic: "hɔɔ nók-hûuk", class: "low" },
];

export default consonants;
